name: Package Application with PyInstaller
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install .
      - name: Package Application with PyInstaller
        run: |
          pyinstaller build\form_filler.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: form_filler_exe
          path: dist/form_filler.exe
          retention-days: 1
          overwrite: true
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: form_filler_exe
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: dist/form_filler.exe
    
